name: Action Tester 

on:
  pull_request:
    branches: [ demo ]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: twerthi/Octopus-Deploy-Action@v1
      with:
        command: "pack"
